import { useEffect,useMemo,useState } from "react";
import { CalendarClock,CheckCircle,RefreshCw,XCircle } from "lucide-react";
import { Button } from "@/components/ui/button";
import { useAuth } from "@/contexts/AuthContext";
import { listBuyerBookings,updateBookingStatus,type Booking } from "@/services/booking.service";
const activeStatuses=["requested","accepted"];
const historyStatuses=["declined","cancelled","completed","no_show","expired"];
const fmt=(v:string)=>new Date(v).toLocaleString();
export default function UserBookingsPage(){
 const {user}=useAuth(); const [items,setItems]=useState<Booking[]>([]); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState<string|null>(null); const [error,setError]=useState("");
 async function load(){if(!user?.$id)return;setLoading(true);setError("");try{setItems(await listBuyerBookings(user.$id));}catch(e){console.error(e);setError("Unable to load your bookings right now.");}finally{setLoading(false);}}
 useEffect(()=>{void load();},[user?.$id]);
 const active=useMemo(()=>items.filter(b=>!b.isArchived&&activeStatuses.includes(b.status)),[items]); const history=useMemo(()=>items.filter(b=>!b.isArchived&&historyStatuses.includes(b.status)),[items]);
 async function cancel(id:string){if(!window.confirm("Cancel this booking request?"))return;setBusy(id);try{const u=await updateBookingStatus(id,"cancelBooking");setItems(x=>x.map(b=>b.$id===id?u:b));}catch(e){console.error(e);setError("Unable to cancel this booking. Please try again.");}finally{setBusy(null);}}
 return <div className="space-y-6"><div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3"><div><h1 className="text-2xl sm:text-3xl font-bold text-gray-900 dark:text-white">My Bookings</h1><p className="text-gray-600 dark:text-gray-400 mt-1">Track service requests and provider responses.</p></div><Button variant="outline" onClick={()=>void load()} disabled={loading} className="w-full sm:w-auto"><RefreshCw className={`w-4 h-4 mr-2 ${loading?"animate-spin":""}`}/>Refresh</Button></div>
 {error&&<div className="p-4 rounded-lg border border-red-200 bg-red-50 text-sm text-red-700">{error}</div>}
 {loading?<div className="py-16 text-center text-gray-400">Loading bookings…</div>:items.length===0?<div className="py-16 text-center text-gray-500"><CalendarClock className="w-10 h-10 mx-auto mb-3 opacity-40"/><p>No bookings yet.</p></div>:<div className="space-y-6"><section><h2 className="font-semibold mb-3">Active ({active.length})</h2>{active.length===0?<p className="text-sm text-gray-500">No active bookings.</p>:<div className="space-y-3">{active.map(b=><BookingCard key={b.$id} booking={b} busy={busy===b.$id} onCancel={cancel}/>)}</div>}</section><section><h2 className="font-semibold mb-3">History ({history.length})</h2>{history.length===0?<p className="text-sm text-gray-500">No booking history.</p>:<div className="space-y-3">{history.map(b=><BookingCard key={b.$id} booking={b} busy={false}/>)}</div>}</section></div>}</div>;
}
function BookingCard({booking,busy,onCancel}:{booking:Booking;busy:boolean;onCancel?:(id:string)=>void}){return <div className="bg-white dark:bg-gray-800 rounded-lg border shadow-sm p-5"><div className="flex flex-col sm:flex-row sm:items-start sm:justify-between gap-3"><div><div className="flex flex-wrap items-center gap-2"><h3 className="font-semibold text-gray-900 dark:text-white">{booking.serviceTitleSnapshot}</h3><span className="px-2 py-0.5 rounded-full bg-yellow-100 text-yellow-700 text-xs capitalize">{booking.status.replace("_"," ")}</span></div><p className="text-sm text-gray-500 mt-1">{fmt(booking.requestedDateTime)}</p></div><p className="font-semibold">₦{booking.priceSnapshot.toLocaleString()}</p></div>{booking.notes&&<p className="text-sm text-gray-600 dark:text-gray-300 mt-3">Notes: {booking.notes}</p>}{booking.status==="accepted"&&<p className="text-sm text-green-700 mt-3 flex items-center gap-2"><CheckCircle className="w-4 h-4"/>Provider accepted your request.</p>}{booking.status==="requested"&&onCancel&&<Button variant="outline" size="sm" className="mt-4" onClick={()=>onCancel(booking.$id)} disabled={busy}><XCircle className="w-4 h-4 mr-2"/>Cancel request</Button>}</div>}
