import { useEffect,useMemo,useState } from "react";
import { Archive,ArchiveRestore,CalendarClock,Check,CheckCircle,RefreshCw,X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { useAuth } from "@/contexts/AuthContext";
import { listProviderBookings,setBookingArchived,updateBookingStatus,type Booking } from "@/services/booking.service";
const activeStatuses=["requested","accepted"]; const historyStatuses=["declined","cancelled","completed","no_show","expired"];
export default function SellerBookings(){const{user}=useAuth();const[items,setItems]=useState<Booking[]>([]);const[loading,setLoading]=useState(true);const[busy,setBusy]=useState<string|null>(null);const[error,setError]=useState("");
async function load(){if(!user?.$id)return;setLoading(true);setError("");try{setItems(await listProviderBookings(user.$id));}catch(e){console.error(e);setError("Unable to load bookings right now.");}finally{setLoading(false);}}useEffect(()=>{void load();},[user?.$id]);
const active=useMemo(()=>items.filter(b=>!b.isArchived&&activeStatuses.includes(b.status)),[items]);const history=useMemo(()=>items.filter(b=>!b.isArchived&&historyStatuses.includes(b.status)),[items]);const archived=useMemo(()=>items.filter(b=>b.isArchived),[items]);
async function mutate(id:string,a:"acceptBooking"|"declineBooking"|"completeBooking"|"noShowBooking"){setBusy(id);try{const u=await updateBookingStatus(id,a);setItems(x=>x.map(b=>b.$id===id?u:b));}catch(e){console.error(e);setError("Unable to update this booking. Please try again.");}finally{setBusy(null);}}async function archive(id:string,v:boolean){setBusy(id);try{const u=await setBookingArchived(id,v);setItems(x=>x.map(b=>b.$id===id?u:b));}catch(e){console.error(e);setError("Unable to update this booking. Please try again.");}finally{setBusy(null);}}
return <div className="space-y-6"><div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3"><div><h1 className="text-2xl sm:text-3xl font-bold">Bookings</h1><p className="text-gray-600 dark:text-gray-400 mt-1">Manage service requests from customers.</p></div><Button variant="outline" onClick={()=>void load()} disabled={loading} className="w-full sm:w-auto"><RefreshCw className="w-4 h-4 mr-2"/>Refresh</Button></div>{error&&<div className="p-4 rounded-lg border border-red-200 bg-red-50 text-sm text-red-700">{error}</div>}<div className="flex flex-wrap gap-2 border-b"><span className="px-3 py-2 text-sm font-medium">Active ({active.length})</span><span className="px-3 py-2 text-sm">History ({history.length})</span><span className="px-3 py-2 text-sm">Archived ({archived.length})</span></div>{loading?<div className="py-16 text-center text-gray-400">Loading bookings…</div>:<div className="space-y-3">{[...active,...history,...archived].map(b=><div key={b.$id} className="bg-white dark:bg-gray-800 rounded-lg border shadow-sm p-5"><div className="flex flex-col lg:flex-row lg:items-start lg:justify-between gap-3"><div><div className="flex flex-wrap items-center gap-2"><h3 className="font-semibold">{b.serviceTitleSnapshot}</h3><span className="px-2 py-0.5 rounded-full bg-yellow-100 text-yellow-700 text-xs capitalize">{b.status.replace("_"," ")}</span></div><p className="text-sm text-gray-600 dark:text-gray-300 mt-1">Customer: {b.customerName} · {b.customerPhone}</p><p className="text-sm text-gray-500 mt-1"><CalendarClock className="inline w-3.5 h-3.5 mr-1"/>{new Date(b.requestedDateTime).toLocaleString()}</p>{b.notes&&<p className="text-sm text-gray-600 mt-2">Notes: {b.notes}</p>}</div><p className="font-semibold">₦{b.priceSnapshot.toLocaleString()}</p></div><div className="flex flex-col sm:flex-row gap-2 mt-4">{b.status==="requested"&&<><Button size="sm" onClick={()=>void mutate(b.$id,"acceptBooking")} disabled={busy===b.$id}><Check className="w-4 h-4 mr-2"/>Accept</Button><Button size="sm" variant="outline" onClick={()=>void mutate(b.$id,"declineBooking")} disabled={busy===b.$id}><X className="w-4 h-4 mr-2"/>Decline</Button></>}{b.status==="accepted"&&<><Button size="sm" onClick={()=>void mutate(b.$id,"completeBooking")} disabled={busy===b.$id}><CheckCircle className="w-4 h-4 mr-2"/>Completed</Button><Button size="sm" variant="outline" onClick={()=>void mutate(b.$id,"noShowBooking")} disabled={busy===b.$id}>No-show</Button></>}{!b.isArchived?<Button size="sm" variant="ghost" onClick={()=>void archive(b.$id,true)} disabled={busy===b.$id}><Archive className="w-4 h-4 mr-2"/>Archive</Button>:<Button size="sm" variant="ghost" onClick={()=>void archive(b.$id,false)} disabled={busy===b.$id}><ArchiveRestore className="w-4 h-4 mr-2"/>Restore</Button>}</div></div>)}</div>}</div>}
