import { Query } from "appwrite";
import { databases, DB_ID, functions } from "@/lib/appwrite/client";

export type BookingStatus = "requested" | "accepted" | "declined" | "cancelled" | "completed" | "no_show" | "expired";
export interface Booking { $id:string; $createdAt:string; buyerId:string; providerId:string; serviceId:string; serviceTitleSnapshot:string; priceSnapshot:number; requestedDateTime:string; customerName:string; customerPhone:string; customerEmail:string|null; serviceMode:string|null; serviceLocation:string|null; notes:string|null; status:BookingStatus; providerResponseAt:string|null; completedAt:string|null; cancelledAt:string|null; cancellationReason:string|null; isArchived:boolean; }
type BookingDocument = Partial<Booking> & {$id:string;$createdAt?:string};
const TABLE="bookings";
const toBooking=(d:BookingDocument):Booking=>({$id:d.$id,$createdAt:d.$createdAt??"",buyerId:String(d.buyerId??""),providerId:String(d.providerId??""),serviceId:String(d.serviceId??""),serviceTitleSnapshot:String(d.serviceTitleSnapshot??""),priceSnapshot:Number(d.priceSnapshot??0),requestedDateTime:String(d.requestedDateTime??""),customerName:String(d.customerName??""),customerPhone:String(d.customerPhone??""),customerEmail:d.customerEmail?String(d.customerEmail):null,serviceMode:d.serviceMode?String(d.serviceMode):null,serviceLocation:d.serviceLocation?String(d.serviceLocation):null,notes:d.notes?String(d.notes):null,status:(d.status??"requested") as BookingStatus,providerResponseAt:d.providerResponseAt?String(d.providerResponseAt):null,completedAt:d.completedAt?String(d.completedAt):null,cancelledAt:d.cancelledAt?String(d.cancelledAt):null,cancellationReason:d.cancellationReason?String(d.cancellationReason):null,isArchived:Boolean(d.isArchived)});
async function execute(operation:string,payload:object){const execution=await functions.createExecution("public-seller-profile",JSON.stringify({operation,...payload}));const body=execution.responseBody?JSON.parse(execution.responseBody):null;if(!body?.ok||!body.booking)throw new Error(body?.error||"Booking request failed.");return toBooking(body.booking);}
export interface CreateBookingRequestInput {serviceId:string;providerId:string;requestedDateTime:string;customerName:string;customerPhone:string;customerEmail?:string|null;serviceMode?:string|null;serviceLocation?:string|null;notes?:string|null;}
export const createBookingRequest=(input:CreateBookingRequestInput)=>execute("createBookingRequest",input);
export const updateBookingStatus=(bookingId:string,action:"acceptBooking"|"declineBooking"|"cancelBooking"|"completeBooking"|"noShowBooking")=>execute(action,{bookingId});
export const setBookingArchived=(bookingId:string,archived:boolean)=>execute(archived?"archiveBooking":"unarchiveBooking",{bookingId});
export async function listBuyerBookings(buyerId:string){const r=await databases.listDocuments(DB_ID,TABLE,[Query.equal("buyerId",buyerId),Query.orderDesc("requestedDateTime"),Query.limit(100)]);return r.documents.map(d=>toBooking(d as unknown as BookingDocument));}
export async function listProviderBookings(providerId:string){const r=await databases.listDocuments(DB_ID,TABLE,[Query.equal("providerId",providerId),Query.orderDesc("requestedDateTime"),Query.limit(100)]);return r.documents.map(d=>toBooking(d as unknown as BookingDocument));}
