import { ID, Permission, Query, Role } from "appwrite";
import { databases, DB_ID, functions } from "@/lib/appwrite/client";
import { getCurrentAccount } from "@/lib/appwrite/account";
export type FeedbackType="feedback"|"complaint"; export type FeedbackStatus="open"|"in-review"|"resolved";
export interface Feedback{$id:string;$createdAt:string;userId:string;userName:string;userEmail:string;type:FeedbackType;subject:string;message:string;orderId:string|null;bookingId:string|null;status:FeedbackStatus;adminNote:string|null;resolvedAt:string|null}
export interface CreateFeedbackInput{type:FeedbackType;subject:string;message:string;orderId?:string|null;bookingId?:string|null}
const TABLE="feedback"; const FN="public-seller-profile";
const account=async()=>{const a=await getCurrentAccount();if(!a?.$id)throw new Error("You must be signed in.");return a};
const status=(v:unknown):FeedbackStatus=>v==="in-review"||v==="resolved"?v:"open";
const map=(d:Record<string,unknown>):Feedback=>({$id:String(d.$id??""),$createdAt:String(d.$createdAt??""),userId:String(d.userId??""),userName:String(d.userName??""),userEmail:String(d.userEmail??""),type:d.type==="complaint"?"complaint":"feedback",subject:String(d.subject??""),message:String(d.message??""),orderId:typeof d.orderId==="string"&&d.orderId?d.orderId:null,bookingId:typeof d.bookingId==="string"&&d.bookingId?d.bookingId:null,status:status(d.status),adminNote:typeof d.adminNote==="string"&&d.adminNote?d.adminNote:null,resolvedAt:typeof d.resolvedAt==="string"&&d.resolvedAt?d.resolvedAt:null});
export async function createFeedback(input:CreateFeedbackInput){const a=await account();if(!input.subject.trim()||!input.message.trim())throw new Error("Subject and message are required.");const d=await databases.createDocument(DB_ID,TABLE,ID.unique(),{userId:a.$id,userName:a.name??"",userEmail:a.email??"",type:input.type,subject:input.subject.trim(),message:input.message.trim(),orderId:input.orderId?.trim()||null,bookingId:input.bookingId?.trim()||null,status:"open",adminNote:null,resolvedAt:null},[Permission.read(Role.user(a.$id)),Permission.update(Role.user(a.$id))]);return map(d as unknown as Record<string,unknown>)}
export async function listMyFeedback(){const a=await account();const r=await databases.listDocuments(DB_ID,TABLE,[Query.equal("userId",a.$id),Query.orderDesc("$createdAt"),Query.limit(100)]);return r.documents.map(d=>map(d as unknown as Record<string,unknown>))}
async function admin(op:string,payload:Record<string,unknown>={}){const e=await functions.createExecution(FN,JSON.stringify({operation:op,...payload}));if(e.responseStatusCode<200||e.responseStatusCode>=300)throw new Error("Could not process the feedback request.");const b=JSON.parse(e.responseBody||"{}");if(!b.ok)throw new Error(b.error||"Could not process the feedback request.");return b}
export async function listAllFeedback(){const b=await admin("listFeedback");return Array.isArray(b.feedback)?b.feedback.map((x:Record<string,unknown>)=>map(x)):[]}
export async function updateFeedbackStatus(id:string,s:FeedbackStatus,n?:string){const b=await admin("updateFeedbackStatus",{feedbackId:id,status:s,adminNote:n?.trim()||null});return map(b.feedback as Record<string,unknown>)}
